### ISSUE TITLE
Improve the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m1-evaluacion-intermedia-claradios#1]
Really cool job @claradios !!!

Here you have some tips to improve the exercise:

## HTML
- [x] Humanize text in `alt` attributes, a sentence without the dash `-` may do the trick ;)

## CSS - structure
- [x] Move the font CSS before your main CSS

## CSS - box model
- [x] Block elements like our main one do not need a width: 100% or width: 100vw property to tell them to do what they are going to do anyway ;)

## CSS - flex
- [x] The main title should be vertically and horizontally centered, try to use flex instead of absolute positions to solve this

## CSS - other
- [x] Avoid uppercase/capital on HTML texts, and `BR` tags we can transform the text with CSS; this way we keep concepts separated, HTML for content, and CSS for styles

Let me know if you have any doubts ;)

Go for it!!

**Comment by claradios** [comment]
Thank you so much for your feedback @oneeyedman !!
I hope everything looks fine now that I've followed your advice. If there is anything else I can do to improve the exercise just let me know. 
Thanks again for your help ;)

**Comment by oneeyedman** [comment]
Hola, @claradios, todavía queda un poco de ajuste para que se vea bien, pero lo doy por bueno para la evaluación
